//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: msg.proto
namespace msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_LoginReq")]
  public partial class CS_LoginReq : global::ProtoBuf.IExtensible
  {
    public CS_LoginReq() {}
    
    private string _AccName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"AccName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AccName
    {
      get { return _AccName; }
      set { _AccName = value; }
    }
    private string _AccPassword;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"AccPassword", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AccPassword
    {
      get { return _AccPassword; }
      set { _AccPassword = value; }
    }
    private msg.EPlatForm _PlatForm;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"PlatForm", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public msg.EPlatForm PlatForm
    {
      get { return _PlatForm; }
      set { _PlatForm = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleBaseInfo")]
  public partial class RoleBaseInfo : global::ProtoBuf.IExtensible
  {
    public RoleBaseInfo() {}
    
    private string _NickName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"NickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string NickName
    {
      get { return _NickName; }
      set { _NickName = value; }
    }
    private int _TemplateId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"TemplateId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int TemplateId
    {
      get { return _TemplateId; }
      set { _TemplateId = value; }
    }
    private int _Level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private int _Sex;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Sex
    {
      get { return _Sex; }
      set { _Sex = value; }
    }
    private long _Gold;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long Gold
    {
      get { return _Gold; }
      set { _Gold = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_LoginResponse")]
  public partial class SC_LoginResponse : global::ProtoBuf.IExtensible
  {
    public SC_LoginResponse() {}
    
    private msg.ELoginResult _LoginResult;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"LoginResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public msg.ELoginResult LoginResult
    {
      get { return _LoginResult; }
      set { _LoginResult = value; }
    }
    private readonly global::System.Collections.Generic.List<msg.RoleBaseInfo> _PlayerBaseInfo = new global::System.Collections.Generic.List<msg.RoleBaseInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"PlayerBaseInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<msg.RoleBaseInfo> PlayerBaseInfo
    {
      get { return _PlayerBaseInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_CreateRoleReq")]
  public partial class CS_CreateRoleReq : global::ProtoBuf.IExtensible
  {
    public CS_CreateRoleReq() {}
    
    private string _NickName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"NickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string NickName
    {
      get { return _NickName; }
      set { _NickName = value; }
    }
    private int _TemplateId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"TemplateId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int TemplateId
    {
      get { return _TemplateId; }
      set { _TemplateId = value; }
    }
    private int _Sex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Sex
    {
      get { return _Sex; }
      set { _Sex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_CreateRoleAck")]
  public partial class SC_CreateRoleAck : global::ProtoBuf.IExtensible
  {
    public SC_CreateRoleAck() {}
    
    private msg.EResultCreateRole _Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public msg.EResultCreateRole Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private readonly global::System.Collections.Generic.List<msg.RoleBaseInfo> _RoleInfo = new global::System.Collections.Generic.List<msg.RoleBaseInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"RoleInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<msg.RoleBaseInfo> RoleInfo
    {
      get { return _RoleInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MSG_ID")]
    public enum MSG_ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ELogin_Req", Value=1001)]
      ELogin_Req = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ELogin_Ack", Value=1002)]
      ELogin_Ack = 1002
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ELoginResult")]
    public enum ELoginResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Succeed", Value=0)]
      Succeed = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"InvalidAccOrPwd", Value=1)]
      InvalidAccOrPwd = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServerClosed", Value=2)]
      ServerClosed = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EPlatForm")]
    public enum EPlatForm
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Android", Value=0)]
      Android = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ios", Value=1)]
      Ios = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Windows", Value=2)]
      Windows = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EResultCreateRole")]
    public enum EResultCreateRole
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eSucceed", Value=0)]
      eSucceed = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eNicknameExsists", Value=1)]
      eNicknameExsists = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eRoleCountLimit", Value=2)]
      eRoleCountLimit = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eUnknownError", Value=3)]
      eUnknownError = 3
    }
  
}