// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: msg.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace Msg
{

    [global::ProtoBuf.ProtoContract(Name = @"CS_LoginReq")]
    public partial class CSLoginReq
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string AccName { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string AccPassword { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public EPlatForm PlatForm { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoleBaseInfo
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string NickName { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public long Gold { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"SC_LoginResponse")]
    public partial class SCLoginResponse
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ELoginResult LoginResult { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public RoleBaseInfo PlayerBaseInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum ELoginResult
    {
        Succeed = 0,
        InvalidAccOrPwd = 1,
        ServerClosed = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum EPlatForm
    {
        Android = 0,
        Ios = 1,
        Windows = 2,
    }

}

#pragma warning restore CS1591, CS0612, CS3021
